#!/usr/bin/env bash
#
# Install (or remove) the Streamplay daemon and Plasma applet for the
# current user. Nothing is written outside $HOME.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/streamplay"
BIN_DIR="$HOME/.local/bin"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
APPLET_ID="io.github.leissa.streamplay"

say()  { printf '\033[1m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33m==>\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31m==>\033[0m %s\n' "$*" >&2; exit 1; }

check_requirements() {
    local missing=()
    command -v python3 >/dev/null || die "Missing requirements: python3"
    command -v kpackagetool6 >/dev/null || missing+=("kpackagetool6 (plasma-workspace)")
    mapfile -t -O ${#missing[@]} missing < <(PYTHONPATH="$HERE/daemon" python3 -m streamplay.check)

    if [ ${#missing[@]} -gt 0 ]; then
        die "Missing requirements: ${missing[*]}"
    fi
}

install_daemon() {
    say "Installing the daemon into $DATA_DIR"
    mkdir -p "$DATA_DIR" "$BIN_DIR"
    rm -rf "${DATA_DIR:?}/streamplay"
    cp -r "$HERE/daemon/streamplay" "$DATA_DIR/streamplay"
    find "$DATA_DIR/streamplay" -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null || true

    cat > "$BIN_DIR/streamplayd" <<EOF
#!/usr/bin/env bash
# Generated by install.sh
export PYTHONPATH="$DATA_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m streamplay "\$@"
EOF
    chmod +x "$BIN_DIR/streamplayd"

    case ":$PATH:" in
        *":$BIN_DIR:"*) ;;
        *) warn "$BIN_DIR is not on your PATH; the systemd unit uses the full path anyway." ;;
    esac
}

install_service() {
    say "Installing the systemd user service"
    mkdir -p "$UNIT_DIR"
    cp "$HERE/systemd/streamplay.service" "$UNIT_DIR/streamplay.service"
    systemctl --user daemon-reload
    systemctl --user enable streamplay.service
    # restart, not "enable --now": on a reinstall the service is already
    # running and would otherwise keep serving the previous code.
    systemctl --user restart streamplay.service
    sleep 1
    if systemctl --user is-active --quiet streamplay.service; then
        say "The service is running."
    else
        warn "The service did not start. Check: journalctl --user -u streamplay -n 40"
    fi
}

install_applet() {
    say "Installing the Plasma applet"
    if kpackagetool6 --type Plasma/Applet --list 2>/dev/null | grep -qx "$APPLET_ID"; then
        kpackagetool6 --type Plasma/Applet --upgrade "$HERE/plasmoid/package"
    else
        kpackagetool6 --type Plasma/Applet --install "$HERE/plasmoid/package"
    fi
}

refresh_plasma() {
    say "Clearing the Plasma cache"
    # Plasma caches compiled QML; an upgraded applet keeps serving the
    # previous code until that cache is gone.
    rm -rf "${XDG_CACHE_HOME:-$HOME/.cache}"/plasma* 2>/dev/null || true

    if ! pgrep -x plasmashell >/dev/null; then
        say "plasmashell is not running; the applet shows up with the next session."
        return
    fi
    say "Restarting plasmashell"
    if systemctl --user is-active --quiet plasma-plasmashell.service; then
        systemctl --user restart plasma-plasmashell.service
    else
        kquitapp6 plasmashell >/dev/null 2>&1 || pkill -x plasmashell || true
        sleep 1
        nohup plasmashell --replace >/dev/null 2>&1 &
    fi
}

uninstall() {
    say "Removing the systemd user service"
    systemctl --user disable --now streamplay.service 2>/dev/null || true
    rm -f "$UNIT_DIR/streamplay.service"
    systemctl --user daemon-reload 2>/dev/null || true

    say "Removing the applet"
    kpackagetool6 --type Plasma/Applet --remove "$APPLET_ID" 2>/dev/null || true

    say "Removing the daemon"
    rm -rf "$DATA_DIR"
    rm -f "$BIN_DIR/streamplayd"

    say "Your servers and settings are untouched in ${XDG_CONFIG_HOME:-$HOME/.config}/streamplay."
}

case "${1:-install}" in
    install)
        check_requirements
        install_daemon
        install_service
        install_applet
        refresh_plasma
        echo
        say "Done. Add the “Streamplay” widget to a panel or the desktop,"
        say "then use its settings to add your music servers."
        ;;
    uninstall|remove)
        uninstall
        ;;
    *)
        die "Usage: $0 [install|uninstall]"
        ;;
esac
